import assert from "node:assert/strict";
import test from "node:test";

import { synchronizeCargoState } from "./cargo-lock.mjs";

function metadata(names) {
  const packages = names.map((name) => ({ id: `workspace#${name}`, name }));
  return {
    packages,
    workspace_members: packages.map(({ id }) => id),
  };
}

function manifest(version = "0.3.0") {
  return `[workspace]
members = ["crates/ragavan", "crates/ragavan-core"]

[workspace.package]
version = "${version}"
edition = "2024"
`;
}

const LOCKFILE = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "external"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "path-helper"
version = "9.8.7"

[[package]]
name = "ragavan"
version = "0.2.1"
dependencies = [
 "ragavan-core",
]

[[package]]
name = "ragavan-core"
version = "0.2.1"
`;

test("synchronizes every workspace package and preserves other packages", () => {
  const result = synchronizeCargoState({
    metadata: metadata(["ragavan", "ragavan-core"]),
    manifest: manifest(),
    lockfile: LOCKFILE,
    releaseVersion: "0.3.0",
  });

  assert.equal(result.packageCount, 2);
  assert.equal(result.version, "0.3.0");
  assert.equal(
    result.lockfile,
    LOCKFILE.replace(
      'name = "ragavan"\nversion = "0.2.1"',
      'name = "ragavan"\nversion = "0.3.0"',
    ).replace(
      'name = "ragavan-core"\nversion = "0.2.1"',
      'name = "ragavan-core"\nversion = "0.3.0"',
    ),
  );
});

test("is idempotent", () => {
  const initial = synchronizeCargoState({
    metadata: metadata(["ragavan", "ragavan-core"]),
    manifest: manifest(),
    lockfile: LOCKFILE,
    releaseVersion: "0.3.0",
  });
  const repeated = synchronizeCargoState({
    metadata: metadata(["ragavan", "ragavan-core"]),
    manifest: manifest(),
    lockfile: initial.lockfile,
    releaseVersion: "0.3.0",
  });

  assert.equal(repeated.lockfile, initial.lockfile);
});

test("requires VERSION and Cargo.toml to agree", () => {
  assert.throws(
    () =>
      synchronizeCargoState({
        metadata: metadata(["ragavan", "ragavan-core"]),
        manifest: manifest("0.2.1"),
        lockfile: LOCKFILE,
        releaseVersion: "0.3.0",
      }),
    /VERSION 0\.3\.0 does not match Cargo\.toml workspace package version 0\.2\.1/,
  );
});

test("requires every workspace member exactly once in Cargo.lock", () => {
  assert.throws(
    () =>
      synchronizeCargoState({
        metadata: metadata(["ragavan", "ragavan-core", "ragavan-runtime"]),
        manifest: manifest(),
        lockfile: LOCKFILE,
        releaseVersion: "0.3.0",
      }),
    /Cargo\.lock is missing workspace packages: ragavan-runtime/,
  );

  assert.throws(
    () =>
      synchronizeCargoState({
        metadata: metadata(["ragavan", "ragavan-core"]),
        manifest: manifest(),
        lockfile: `${LOCKFILE}\n[[package]]\nname = "ragavan"\nversion = "0.2.1"\n`,
        releaseVersion: "0.3.0",
      }),
    /Cargo\.lock contains duplicate workspace package ragavan/,
  );
});

test("rejects registry packages masquerading as workspace members", () => {
  assert.throws(
    () =>
      synchronizeCargoState({
        metadata: metadata(["ragavan", "external"]),
        manifest: manifest(),
        lockfile: LOCKFILE,
        releaseVersion: "0.3.0",
      }),
    /Cargo\.lock workspace package external has a source/,
  );
});
