[package]
name = "ragavan-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
ragavan-adapters = { path = "../ragavan-adapters" }
ragavan-core = { path = "../ragavan-core" }
ragavan-platform = { path = "../ragavan-platform" }

[lints]
workspace = true
